##########################################################################
# THIS FILE SHOULD LIVE IN .terrateam/config.yml
##########################################################################
access_control:
  enabled: true
  apply_require_all_dirspace_access: true
  plan_require_all_dirspace_access: false
  terrateam_config_update: ['*']
  unlock: ['*']
  policies:
    - tag_query: ''
      apply: ['*']
      apply_autoapprove: []
      apply_force: []
      apply_with_superapproval: []
      plan: ['*']
      superapproval: []
apply_requirements:
  checks:
    approved:
      enabled: false
      count: 1
    merge_conflicts:
      enabled: true
    status_checks:
      enabled: true
      ignore_matching: []
  create_pending_apply_check: true
automerge:
  enabled: false
  delete_branch: false
checkout_strategy: merge
cost_estimation:
  enabled: true
  provider: infracost
  currency: USD
default_tf_version: latest
destination_branches:
dirs:
enabled: true
hooks:
  plan:
    pre: []
    post: []
  apply:
    pre: []
    post: []
parallel_runs: 3
version: "1"
when_modified:
  file_patterns: ["**/*.tf", "**/*.tfvars"]
  autoplan: true
  autoplan_draft_pr: true
  autoapply: false
workflows:
